### ISSUE TITLE
Vba2Graph not Working

### ISSUE THREAD

**Issue by leovipin1** [MalwareCantFly/Vba2Graph#8]
I have followed all the steps to install the required softwares and requirements, but i am getting below error in Windows 11 and with python3

C:\Data\Vba2Graph-master\Vba2Graph-master>python vba2graph.py -f "c:\Data\VKs Life OS ER Build\VKs Life OS ER Build App.xlsm" -c 2
XLMMacroDeobfuscator: pywin32 is not installed (only is required if you want to use MS Excel)
INFO:-vba2graph-:Extracting macros from file
INFO:-vba2graph-:Parsing olevba content
INFO:-vba2graph-:Generating output files
Traceback (most recent call last):
  File "C:\Data\Vba2Graph-master\Vba2Graph-master\vba2graph.py", line 1101, in <module>
    main()
  File "C:\Data\Vba2Graph-master\Vba2Graph-master\vba2graph.py", line 1096, in main
    vba2graph_gen(input_vba_content, output_folder, input_file_name, color_scheme)
  File "C:\Data\Vba2Graph-master\Vba2Graph-master\vba2graph.py", line 1011, in vba2graph_gen
    process = Popen(['dot', '-Tpng', dot_output_path, '-o', png_output_path])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I511560\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\I511560\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by leovipin1** [comment]
When i try the same from python2 i get the below error

C:\Data\VKs Life OS ER Build>python c:\Data\Vba2Graph-master\Vba2Graph-master\vba2graph.py -f "VKs Life OS ER Build App.xlsm"-c 2
Traceback (most recent call last):
  File "c:\Data\Vba2Graph-master\Vba2Graph-master\vba2graph.py", line 32, in <module>
    import regex as re
ImportError: No module named regex

**Comment by leovipin1** [comment]
The issue is resolved the pywin32 was missing... it worked after installing the same...

**Comment by leovipin1** [comment]
The issue is resolved the pywin32 was missing... it worked after installing the same...
